#!/usr/bin/env python3
"""
Importer for SEPA pain.001.001.03 payroll payment XMLs.

Each XML is a payment batch generated by the gestoria with one CdtTrfTxInf per
employee transfer. We create a single account.move (journal entry) per file:

  DR 640000 Sueldos y salarios       (one line per employee, with partner)
  CR 572xxx Banco                    (one line, total)

NOTE: SEPA only carries the NET paid. Gross + retenciones IRPF + SS-empleado
are NOT in this file (they live in the proper nomina document). The user should
adjust later, or wire in additional lines from the matching nomina PDF.

Usage:
  python3 sepa_xml_importer.py --file /path/to/SXXXXXX.XML
"""
import argparse
import json
import logging
import sys
from pathlib import Path
from xml.etree import ElementTree as ET
from datetime import datetime

ODOO_PATH = "/opt/odoo17/odoo"
ODOO_CONF = "/etc/odoo17.conf"
DB_NAME = "cararjfam"
DEFAULT_SALARY_ACCOUNT = "640000"

sys.path.insert(0, ODOO_PATH)
import odoo  # noqa: E402
from odoo.api import Environment  # noqa: E402

NS = {"p": "urn:iso:std:iso:20022:tech:xsd:pain.001.001.03"}

log = logging.getLogger("sepa_xml")
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")


def _normalize_acc(s: str) -> str:
    return "".join(c for c in (s or "") if c.isalnum()).upper()


def _strip_dni_prefix(s: str) -> str:
    s = (s or "").strip().upper()
    if s.startswith("ES") and len(s) > 9:
        s = s[2:]
    return s


def parse_xml(path: Path) -> dict:
    tree = ET.parse(path)
    root = tree.getroot()
    init = root.find(".//p:CstmrCdtTrfInitn", NS)
    grp = init.find("p:GrpHdr", NS)
    msg_id = grp.findtext("p:MsgId", default="", namespaces=NS)
    cre_dt = grp.findtext("p:CreDtTm", default="", namespaces=NS)
    initg_party = grp.find("p:InitgPty/p:Nm", NS)
    initg_name = initg_party.text if initg_party is not None else ""
    pi = init.find("p:PmtInf", NS)
    exec_date = pi.findtext("p:ReqdExctnDt", default="", namespaces=NS)
    debtor_iban = pi.findtext(".//p:DbtrAcct/p:Id/p:IBAN", default="", namespaces=NS)
    ctrl_sum = float(pi.findtext("p:CtrlSum", default="0", namespaces=NS) or "0")

    transfers = []
    for tx in pi.findall("p:CdtTrfTxInf", NS):
        amt_node = tx.find("p:Amt/p:InstdAmt", NS)
        amt = float(amt_node.text) if amt_node is not None and amt_node.text else 0.0
        cdtr_name = tx.findtext("p:Cdtr/p:Nm", default="", namespaces=NS) or ""
        cdtr_id = tx.findtext(".//p:PrvtId/p:Othr/p:Id", default="", namespaces=NS) or ""
        cdtr_iban = tx.findtext("p:CdtrAcct/p:Id/p:IBAN", default="", namespaces=NS) or ""
        ref = tx.findtext("p:RmtInf/p:Ustrd", default="", namespaces=NS) or "Nomina"
        end_to_end = tx.findtext("p:PmtId/p:EndToEndId", default="", namespaces=NS) or ""
        transfers.append({
            "name": cdtr_name.strip(),
            "vat": _strip_dni_prefix(cdtr_id),
            "iban": _normalize_acc(cdtr_iban),
            "amount": amt,
            "ref": ref,
            "end_to_end": end_to_end,
        })

    return {
        "msg_id": msg_id,
        "exec_date": exec_date,
        "debtor_name": initg_name,
        "debtor_iban": _normalize_acc(debtor_iban),
        "ctrl_sum": ctrl_sum,
        "transfers": transfers,
    }


def _find_journal_by_iban(env, iban: str):
    iban = _normalize_acc(iban)
    for j in env["account.journal"].search([("type", "=", "bank")]):
        if not j.bank_account_id:
            continue
        acc = _normalize_acc(j.bank_account_id.acc_number or "")
        if acc and (acc == iban or acc.endswith(iban[-10:]) or iban.endswith(acc[-10:])):
            return j
    return None


def _find_or_create_employee_partner(env, name: str, dni: str, iban: str = ""):
    if dni:
        p = env["res.partner"].search([("vat", "=", dni)], limit=1)
        if p:
            return p
    p = env["res.partner"].search([("name", "=", name)], limit=1)
    if p:
        if dni and not p.vat:
            try:
                p.vat = dni
            except Exception:
                pass
        return p
    es = env.ref("base.es", raise_if_not_found=False)
    return env["res.partner"].create({
        "name": name,
        "vat": dni or False,
        "is_company": False,
        "country_id": es.id if es else False,
        "company_id": False,
    })


def import_file(file_path: Path) -> dict:
    parsed = parse_xml(file_path)
    log.info(f"parsed {file_path.name}: {len(parsed['transfers'])} transfers, total {parsed['ctrl_sum']:.2f}")

    odoo.tools.config.parse_config(["-c", ODOO_CONF])
    registry = odoo.registry(DB_NAME)
    with registry.cursor() as cr:
        env = Environment(cr, odoo.SUPERUSER_ID, {"tz": "Europe/Madrid"})
        bank_journal = _find_journal_by_iban(env, parsed["debtor_iban"])
        if not bank_journal:
            return {"error": f"no bank journal matches {parsed['debtor_iban']!r}"}
        company_id = bank_journal.company_id.id

        misc_journal = env["account.journal"].search([
            ("type", "=", "general"), ("company_id", "=", company_id)
        ], limit=1) or bank_journal

        salary_account = env["account.account"].search([
            ("code", "=", DEFAULT_SALARY_ACCOUNT), ("company_id", "=", company_id)
        ], limit=1)
        if not salary_account:
            return {"error": f"no account {DEFAULT_SALARY_ACCOUNT} in company {company_id}"}

        bank_account = bank_journal.default_account_id
        if not bank_account:
            return {"error": f"bank journal {bank_journal.id} has no default_account"}

        exec_date = datetime.strptime(parsed["exec_date"], "%Y-%m-%d").date() if parsed["exec_date"] else datetime.now().date()
        ref = f"Nomina SEPA {parsed['msg_id']}"

        # Idempotency check
        existing = env["account.move"].search([
            ("ref", "=", ref), ("company_id", "=", company_id)
        ], limit=1)
        if existing:
            log.warning(f"idempotency: move id={existing.id} already exists for ref={ref!r}")
            return {
                "duplicate": True,
                "move_id": existing.id,
                "ref": ref,
                "company_id": company_id,
            }

        line_vals = []
        for t in parsed["transfers"]:
            partner = _find_or_create_employee_partner(env, t["name"], t["vat"], t["iban"])
            line_vals.append((0, 0, {
                "name": f"Nomina {t['name']} {exec_date.isoformat()}",
                "partner_id": partner.id,
                "account_id": salary_account.id,
                "debit": t["amount"],
                "credit": 0.0,
            }))
        line_vals.append((0, 0, {
            "name": f"Pago nominas SEPA {parsed['msg_id']} ({len(parsed['transfers'])} empleados)",
            "account_id": bank_account.id,
            "debit": 0.0,
            "credit": parsed["ctrl_sum"],
        }))

        move = env["account.move"].with_company(company_id).create({
            "move_type": "entry",
            "journal_id": misc_journal.id,
            "company_id": company_id,
            "date": exec_date,
            "ref": ref,
            "narration": (
                f"Asiento generado automaticamente de SEPA pain.001 ({file_path.name}).\n"
                f"Importes son LIQUIDOS pagados al empleado.\n"
                f"Faltan: bruto, retenciones IRPF, cotizacion SS empleado (anadir desde nomina).\n"
                f"Confianza: 0.95"
            ),
            "line_ids": line_vals,
        })
        log.info(f"created account.move id={move.id}")
        try:
            move.action_post()
            posted = True
        except Exception as e:
            log.warning(f"auto-post failed for move id={move.id}: {e}")
            posted = False

        cr.commit()
        return {
            "move_id": move.id,
            "posted": posted,
            "ref": ref,
            "company_id": company_id,
            "transfers": len(parsed["transfers"]),
            "total": parsed["ctrl_sum"],
        }


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--file", required=True)
    args = p.parse_args()

    fp = Path(args.file)
    if not fp.exists():
        log.error(f"file not found: {fp}")
        return 40

    try:
        result = import_file(fp)
    except Exception as e:
        log.exception("import error")
        print(f"ERROR={type(e).__name__}: {e}")
        return 30

    print(f"SEPA_RESULT={json.dumps(result, ensure_ascii=False, default=str)}")
    if result.get("error"):
        return 10
    return 0


if __name__ == "__main__":
    sys.exit(main())
